package name.teemo.pogo.utils;

public class PokemonName {
	
	public static String[] pokemonNameID = {
			"001","002","003","004","005","006","007","008","009","010",
			"011","012","013","014","015","016","017","018","019","020",
			"021","022","023","024","025","026","027","028","029","030",
			"031","032","033","034","035","036","037","038","039","040",
			"041","042","043","044","045","046","047","048","049","050",
			"051","052","053","054","055","056","057","058","059","060",
			"061","062","063","064","065","066","067","068","069","070",
			"071","072","073","074","075","076","077","078","079","080",
			"081","082","083","084","085","086","087","088","089","090",
			"091","092","093","094","095","096","097","098","099","100",
			"101","102","103","104","105","106","107","108","109","110",
			"111","112","113","114","115","116","117","118","119","120",
			"121","122","123","124","125","126","127","128","129","130",
			"131","132","133","134","135","136","137","138","139","140",
			"141","142","143","144","145","146","147","148","149","150",
			"151"};
	public static String[] pokemonNameCN = {
			"妙蛙种子","妙蛙草","妙蛙花","小火龙","火恐龙",
			"喷火龙","杰尼龟","卡咪龟","水箭龟","绿毛虫",
			"铁甲蛹","巴大蝶","独角虫","铁壳蛹","大针蜂",
			"波波","比比鸟","大比鸟","小拉达","拉达",
			"烈雀","大嘴雀","阿柏蛇","阿柏怪","皮卡丘",
			"雷丘","穿山鼠","穿山王","尼多兰","尼多娜",
			"尼多后","尼多朗","尼多力诺","尼多王","皮皮",
			"皮可西","六尾","九尾","胖丁","胖可丁",
			"超音蝠","大嘴蝠","走路草","臭臭花","霸王花",
			"派拉斯","派拉斯特","毛球","摩鲁蛾","地鼠",
			"三地鼠","喵喵","猫老大","可达鸭","哥达鸭",
			"猴怪","火暴猴","卡蒂狗","风速狗","蚊香蝌蚪",
			"蚊香君","蚊香泳士","凯西","勇基拉","胡地",
			"腕力","豪力","怪力","喇叭芽","口呆花",
			"大食花","玛瑙水母","毒刺水母","小拳石","隆隆石",
			"隆隆岩","小火马","烈焰马","呆呆兽","呆壳兽",
			"小磁怪","三合一磁怪","大葱鸭","嘟嘟","嘟嘟利",
			"小海狮","白海狮","臭泥","臭臭泥","大舌贝",
			"刺甲贝","鬼斯","鬼斯通","耿鬼","大岩蛇",
			"催眠貘","引梦貘人","大钳蟹","巨钳蟹","霹雳电球",
			"顽皮雷弹","蛋蛋","椰蛋树","卡拉卡拉","嘎啦嘎啦",
			"飞腿郎","快拳郎","大舌头","瓦斯弹","双弹瓦斯",
			"独角犀牛","钻角犀兽","吉利蛋","蔓藤怪","袋兽",
			"墨海马","海刺龙","角金鱼","金鱼王","海星星",
			"宝石海星","魔墙人偶","飞天螳螂","迷唇姐","电击兽",
			"鸭嘴火兽","凯罗斯","肯泰罗","鲤鱼王","暴鲤龙",
			"拉普拉斯","百变怪","伊布","水伊布","雷伊布",
			"火伊布","多边兽","菊石兽","多刺菊石兽","化石盔",
			"镰刀盔","化石翼龙","卡比兽","急冻鸟","闪电鸟",
			"火焰鸟","迷你龙","哈克龙","快龙","超梦",
			"梦幻"};
	public static String[] pokemonNameJP = {
			"フシギダネ","フシギソウ","フシギバナ","ヒトカゲ","リザード",
			"リザードン","ゼニガメ","カメール","カメックス","キャタピー",
			"トランセル","バタフリー","ビードル","コクーン","スピアー",
			"ポッポ","ピジョン","ピジョット","コラッタ","ラッタ",
			"オニスズメ","オニドリル","アーボ","アーボック","ピカチュウ",
			"ライチュウ","サンド","サンドパン","ニドラン♀","ニドリーナ",
			"ニドクイン","ニドラン♂","ニドリーノ","ニドキング","ピッピ",
			"ピクシー","ロコン","キュウコン","プリン","プクリン",
			"ズバット","ゴルバット","ナゾノクサ","クサイハナ","ラフレシア",
			"パラス","パラセクト","コンパン","モルフォン","ディグダ",
			"ダグトリオ","ニャース","ペルシアン","コダック","ゴルダック",
			"マンキー","オコリザル","ガーディ","ウインディ","ニョロモ",
			"ニョロゾ","ニョロボン","ケーシィ","ユンゲラー","フーディン",
			"ワンリキー","ゴーリキー","カイリキー","マダツボミ","ウツドン",
			"ウツボット","メノクラゲ","ドククラゲ","イシツブテ","ゴローン",
			"ゴローニャ","ポニータ","ギャロップ","ヤドン","ヤドラン",
			"コイル","レアコイル","カモネギ","ドードー","ドードリオ",
			"パウワウ","ジュゴン","ベトベター","ベトベトン","シェルダー",
			"パルシェン","ゴース","ゴースト","ゲンガー","イワーク",
			"スリープ","スリーパー","クラブ","キングラー","ビリリダマ",
			"マルマイン","タマタマ","ナッシー","カラカラ","ガラガラ",
			"サワムラー","エビワラー","ベロリンガ","ドガース","マタドガス",
			"サイホーン","サイドン","ラッキー","モンジャラ","ガルーラ",
			"タッツー","シードラ","トサキント","アズマオウ","ヒトデマン",
			"スターミー","バリヤード","ストライク","ルージュラ","エレブー",
			"ブーバー","カイロス","ケンタロス","コイキング","ギャラドス",
			"ラプラス","メタモン","イーブイ","シャワーズ","サンダース",
			"ブースター","ポリゴン","オムナイト","オムスター","カブト",
			"カブトプス","プテラ","カビゴン","フリーザー","サンダー",
			"ファイヤー","ミニリュウ","ハクリュー","カイリュー","ミュウツー",
			"ミュウ"};
	public static String[] pokemonNameUS = {
			"Bulbasaur","Ivysaur","Venusaur","Charmander","Charmeleon",
			"Charizard","Squirtle","Wartortle","Blastoise","Caterpie",
			"Metapod","Butterfree","Weedle","Kakuna","Beedrill",
			"Pidgey","Pidgeotto","Pidgeot","Rattata","Raticate",
			"Spearow","Fearow","Ekans","Arbok","Pikachu",
			"Raichu","Sandshrew","Sandslash","Nidoran♀","Nidorina",
			"Nidoqueen","Nidoran♂","Nidorino","Nidoking","Clefairy",
			"Clefable","Vulpix","Ninetales","Jigglypuff","Wigglytuff",
			"Zubat","Golbat","Oddish","Gloom","Vileplume",
			"Paras","Parasect","Venonat","Venomoth","Diglett",
			"Dugtrio","Meowth","Persian","Psyduck","Golduck",
			"Mankey","Primeape","Growlithe","Arcanine","Poliwag",
			"Poliwhirl","Poliwrath","Abra","Kadabra","Alakazam",
			"Machop","Machoke","Machamp","Bellsprout","Weepinbell",
			"Victreebel","Tentacool","Tentacruel","Geodude","Graveler",
			"Golem","Ponyta","Rapidash","Slowpoke","Slowbro",
			"Magnemite","Magneton","Farfetch'd","Doduo","Dodrio",
			"Seel","Dewgong","Grimer","Muk","Shellder",
			"Cloyster","Gastly","Haunter","Gengar","Onix",
			"Drowzee","Hypno","Krabby","Kingler","Voltorb",
			"Electrode","Exeggcute","Exeggutor","Cubone","Marowak",
			"Hitmonlee","Hitmonchan","Lickitung","Koffing","Weezing",
			"Rhyhorn","Rhydon","Chansey","Tangela","Kangaskhan",
			"Horsea","Seadra","Goldeen","Seaking","Staryu",
			"Starmie","Mr. Mime","Scyther","Jynx","Electabuzz",
			"Magmar","Pinsir","Tauros","Magikarp","Gyarados",
			"Lapras","Ditto","Eevee","Vaporeon","Jolteon",
			"Flareon","Porygon","Omanyte","Omastar","Kabuto",
			"Kabutops","Aerodactyl","Snorlax","Articuno","Zapdos",
			"Moltres","Dratini","Dragonair","Dragonite","Mewtwo",
			"Mew"};

	public static String getPokemonName(String name,String lang){
		for(int i = 0 ; i < pokemonNameUS.length ; i++){
			if(pokemonNameUS[i].toUpperCase().equals(name)){
				if(lang.equals("ID"))return pokemonNameID[i];
				if(lang.equals("CN"))return pokemonNameCN[i];
				if(lang.equals("JP"))return pokemonNameJP[i];
				if(lang.equals("US"))return pokemonNameUS[i];
			}
		}
		return name;
	}
}
